
<script>
// wait for the DOM to be loaded
$(document).ready(function() {
    // bind 'myForm' and provide a simple callback function
    $('#myForm').ajaxForm(function() {
        //alert("Thank you for your comment!");
    });
});
</script>

<?php
$title = 'Criação de Percurso';
$this->headTitle($title);

echo $this->headScript()
->prependFile($this->basePath('js/jquery.form.js'));
$form->setAttribute('action', $this->url('percurso', array(
    'action' => 'add'
)));
?>

<h4>Criação de percurso</h4>

<form id="myForm" name="percurso" id="percurso" action="&#x2F;PortoVisitas&#x2F;percurso&#x2F;add" method="post"> 
    Name: <input type="text" name="name" /> 
    Comment: <textarea name="comment"></textarea> 
    <input type="submit" value="Submit Comment" /> 
</form>