<?php
$title = 'Criação de Percurso';
$this->headTitle($title);

$this->headScript()
    ->prependFile($this->basePath('js/jquery.form.js'))
    ->prependFile($this->basePath('js/util.js'));

// $form->setAttribute('action', $this->url('percurso', array(
// 'action' => 'add'
// )));
?>

<h4><?php echo $this->escapehtml($title)?></h4>
<p>&nbsp;</p>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div id="formDiv" class="container col-sm-8">
<?php

echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('creator'));
echo $this->formHidden($form->get('finishHour'));
echo $this->formHidden($form->get('percursoPoisOrder'));
echo $this->formHidden($form->get('poiList'));
?>

	<div id="errorDiv" style="display: none;">
		<label class="control-label col-xs-4">Não foi possível gerar um
			percurso.</label>
	</div>

	<div class="form-group">
		<label for="name" class="control-label col-xs-4">Nome</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('name'));?>
	</div>
	</div>


	<div class="form-group">
		<label for="description" class="control-label col-xs-4">Descrição</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('description'));?>
	</div>
	</div>

	<div class="form-group">
		<label for="horaInicialVisita" class="control-label col-xs-4">Hora de
			início</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('horaInicialVisita'));?>
	</div>
	</div>

	<div class="form-group">
		<label for="tipoVeiculo" class="control-label col-xs-4">Tipo de
			veículo</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('tipoVeiculo'));?>
	</div>
	</div>

	<div class="form-group">
		<label for="inclinacaoMax" class="control-label col-xs-4">Inclinação
			máxima (%)</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('inclinacaoMax'));?>
	</div>
	</div>

	<div class="form-group">
		<label for="kilometrosMax" class="control-label col-xs-4">Distância
			máxima (km)</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('kilometrosMax'));?>
	</div>
	</div>

	<div class="form-group">
		<label for="poiOrigem" class="control-label col-xs-4">Escolha o ponto
			de origem</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('poiOrigem'));?>
	</div>
	</div>

	<div class="form-group">
		<label for="typeOfSuggestion" class="control-label col-xs-4">Como
			pretende definir o percurso?</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('typeOfSuggestion'));?>
	</div>
	</div>

	<div id="poisCheckBox" class="form-group">
		<label for="percursoPOIs" class="control-label col-xs-4">Seleccione os
			Pontos de Interesse a percorrer</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('percursoPOIs'));?>
	</div>
	</div>

	<div id="durationRadioButtons" class="form-group">
		<label for="maxHorasVisita" class="control-label col-xs-4">Seleccione
			a duração máxima (horas)</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('maxHorasVisita'));?>
	</div>
	</div>

	<p>&nbsp;</p>

	<div class="form-group">
		<div class="col-xs-10" style="margin-left: 21%">
			<a href='<?php echo $this->url('percurso');?>' id="cancel"
				class="btn btn-default">Cancelar</a>
		<?php //echo $this->formSubmit($form->get('submit'));?>
		<a id="generateButton" class="btn btn-primary" href="#" role="button" onclick="generate();">Gerar Percurso</a>
		<?php echo $this->formSubmit($form->get('submitPercurso'));?>
	</div>
	</div>

</div>
<!-- End of form div -->


<div id="gerado" class="col-sm-4" style="display: none;">

	<div id="resultsList"></div>
	<div id="dataDiv" class="col-sm-12"></div>
<!-- 	<div id="buttonsDiv" class="form-group"> 
		<div align="center"> 
			<a id="backB" style="margin-left: -3px;" class="btn btn-default"
 				href="#" role="button">Cancelar</a> 
				<?php //echo $this->formSubmit($form->get('submitPercurso'));?>
				<!-- <a id="savePercurso" style="margin-left: 4px;" class="btn btn-primary" href="#" role="button">Guardar</a> 
 		</div> 
 	</div> -->

</div>

<?php echo $this->form()->closeTag();?>

<div class="modal"></div>


<script type="text/javascript">



var PERCURSO;
var FORM;
var FINALPOST = false;

$body = $("body");

$(document).on({
    ajaxStart: function() { $body.addClass("loading");    },
     ajaxStop: function() { $body.removeClass("loading"); }    
});


function showRequest(formData, jqForm, options) { 
    var queryString = $.param(formData); 
 	console.log(queryString);
    return true; 
} 
 
function showResponse(responseText, statusText, xhr, $form)  { 
    console.log(JSON.stringify(responseText));
    showResult(responseText, statusText, xhr, $form);
} 

function getOptions() {
	var uri, callBackBefore = showRequest, callBackAfter = showResponse;
	if (FINALPOST) {
		uri = 'add';
		callBackBefore = savePercurso;
		callBackAfter = function(){window.location.href='/PortoVisitas/percurso';return true;}
	} else {
		FINALPOST = true;
		var option = $('input[name=typeOfSuggestion]:radio').fieldValue(); 
		if (option == 0)
			uri = 'generatePois';
		else if (option == 1)
			uri = 'generateTime';
	}
	var options = {
			beforeSerialize: callBackBefore,
			beforeSubmit:	showRequest,
	        success:       callBackAfter,
	        url:		'/PortoVisitas/percurso/'+uri,
	        timeout:   30000 
	    };
    return options;
}


function showResult(response, statusText, xhr, $form) {
	var errorDiv = $("#errorDiv")[0];
	if (response.hasOwnProperty('httpStatus')) {
		showDiv(errorDiv);
		return;
	} else if (typeof response.percurso == 'undefined') {
		var err = response.Messages;
		var keys = Object.keys(err).map(function (key) { return key; });
		var str = "Deve preencher os seguintes campos:";
		for (var i=0;i<keys.length;i++) {
			str += "\n\n"+keys[i];
		}
		alert(str);
	} else {
		hideDiv(errorDiv);
	}
	PERCURSO = response;
	FORM = $form;
	console.log("FORM:");
	console.log(FORM);
	var pois = [];
	var list = "<ul class='list-group'>";
	for (var i = 0; i < response.percurso.length; i++) {
		var poi = new Object();
		poi.id = response.percurso[i];
		poi.name = $('input[name="percursoPOIs[]"][value='+poi.id+']').parent().text();
		pois.push(poi);
		list += '<li class="list-group-item">'+poi.name+'<span class="badge">'+(i+1)+'</span></li>';
	}
	const poiList = [...new Set(pois.map(item => item.id))];
	document.getElementById("poiList").value = poiList;
	list += "</ul>";
	$("#resultsList").empty();
	$("#resultsList").append(list);

	var courseData = '<div class="form-group"><div align="center">';
	
	courseData += '<label class="col-sm-12">Duração Total</label>';
	var dur = convertMinsToHrsMins(response.duracao);
	courseData += '<span class="col-sm-12 form-control">'+dur+'</span></div></div>';

	courseData += '<div class="form-group"><div align="center">';
	courseData += '<label class="col-sm-12">Distância Percorrida</label>';
	if (response.kilometros < 1.0)
		courseData += '<span class="col-sm-12 form-control">'+ (response.kilometros*1000).toFixed(0) +' metros</span>';
	else
		courseData += '<span class="col-sm-12  form-control">'+ parseFloat(response.kilometros).toFixed(2) +' Kilometros</span>';
	courseData += '</div></div>';
	$("#dataDiv").empty();
	$("#dataDiv").append(courseData);

	$('#backB').click( function(e) {
		e.preventDefault();
		var thisDiv = $("#gerado")[0];
		hideDiv(thisDiv);
		return false;
		} );

	//$('#savePercurso').click(function(e){ e.preventDefault(); savePercurso(); return false; });
	
	var resultsDiv = $("#gerado")[0];
	showDiv(resultsDiv);
	enableSaving();
	$('#generateButton').text('Gerar Novamente');
}

function enableSaving() {
	$('#savePercurso').prop('disabled', false);
}

function generate() {
	FINALPOST = false;
	$('#percursoForm').submit();
}

function savePercurso() {
	console.log("SAVEPERCURSO!!!!!");
	var startHour = $('#formStartHour').val();
	console.log("STart HOUR-> "+startHour);
	var time = startHour.split(":");
	var startHourObj = new Date();
	startHourObj.setHours(time[0], time[1], 0, 0);
	var duration = Math.floor(PERCURSO.duracao);
	var finishHour = new Date(startHourObj.getTime() + duration*60000);
	var finishTime = finishHour.getHours()+":"+finishHour.getMinutes();
	console.log("FINISH HOUR-> "+finishTime);
	document.getElementById("formFinishHour").value = finishTime;
	document.getElementById("formPercursoPoisOrder").value = PERCURSO.percurso.join();
	return true;
}

$(document).ready(function() { 
	
	$('#percursoForm').submit(function() { 
		options = getOptions();
		
	    console.log("POST URI: "+options);
        $(this).ajaxSubmit(options); 
        return false; 
    });
	
    $("input[name=typeOfSuggestion]:radio").change(function () {
    	multicheck = $("#poisCheckBox")[0];
    	radios = $("#durationRadioButtons")[0];
        if (document.getElementById("choosePois").checked) {
        	hideDiv(radios);
        	showDiv(multicheck);
        }
        else {
            hideDiv(multicheck);
            showDiv(radios);
        }
    });
  
});
</script>







