<?php
$title = $percurso['Name'];
$this->headTitle('Detalhes - '.$title);
?>

<h4><?php echo $this->escapehtml($title);?></h4>
<p>&nbsp;</p>


<table class="table">
	<tr>
		<th>Descrição</th>
		<th>Início</th>
		<th>Fim</th>
		<th>Criador</th>

	</tr>
	<tr>
		<td><?php echo $this->escapeHtml($percurso['Description']);?></td>
		<?php 
        $dateI = new DateTime($percurso['StartHour']);
        $dateF = new DateTime($percurso['FinishHour']);
        $datastrI = $dateI->format('H:i');
        $datastrF = $dateF->format('H:i');
 		?>
 		<td><?php echo $this->escapeHtml($datastrI);?></td>
 		<td><?php echo $this->escapeHtml($datastrF);?></td>
 		<td><?php echo $this->escapeHtml($percurso['Creator']);?></td>
	</tr>
</table>
<p>

<?php $poisOrder = explode(',', $percurso['PercursoPOIsOrder']) ; //  Stored as string as of this moment
 	  $poiCounter = 0;
?>

<h4>Trajecto</h4>
<p>
<ul class="list-group">
    <?php foreach ($poisOrder as $poiIDstr) : ?>
    	<?php
        	$poiID = intval($poiIDstr);
        	$key = array_search($poiID, array_column($percurso['PercursoPOIs'], 'ID'));
        	if ($key === FALSE)
        	    continue;
        	$poiName = $percurso['PercursoPOIs'][$key]['Name'];
    	?>
        <li class="list-group-item"><?php echo $poiName ;?><span class="badge"><?php echo ++$poiCounter ;?></span></li>
    <?php endforeach;?>
</ul>
<p>&nbsp;</p>
<div class="form-group">
	<div class="col-xs-2">
		<button onclick="window.location.href='<?php echo $this->url('percurso');?>'" class="btn btn-default"><span>Voltar</span></button>
	</div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>


