<?php
$title = 'Percursos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
 <a href="<?php echo $this->url('percurso', array('action'=>'add'));?>">Adicionar novo percurso</a>
</p>

<table class="table">
	<tr>
		<th>Nome</th>
		<th>Descricao</th>
		<th>Data</th>
		<th>Criador</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($percursos as $percurso) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($percurso['Name']);?></td>
 		<td><?php echo $this->escapeHtml($percurso['Description']);?></td>
 		<?php 
 		$date = date_parse($percurso['StartHour']);
 		$datastr = $date['year']."-".$date['month']."-".$date['day']." ".$date['hour'].":".$date['minute'];
 		?>
 		<td><?php echo $this->escapeHtml($datastr);?></td>
 		<td><?php echo $this->escapeHtml($percurso['Creator']);?></td>
	 	<td>
	 		<a href="<?php echo $this->url('percurso',
                array('action'=>'index', 'id' => $percurso['id']));?>">Detalhes</a>
		</td>
	</tr>
<?php endforeach; ?>
</table>
