
        <?php
        $title = 'Sugerir Ponto de Interesse';
        $this->headTitle($title);
        
        echo $this->headLink()->prependStylesheet($this->basePath('css/jquery.tag-editor.css'));
        
        echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.tag-editor.min.js'))
            ->prependFile($this->basePath('js/jquery.caret.min.js'));
        ?>

<h3><?php echo $this->escapeHtml($title); ?></h3>


<?php
$form->setAttribute('action', $this->url('poi', array(
    'action' => 'add'
)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('poiid'));
echo $this->formHidden($form->get('creator'));
?>

<div class="form-group">
	<label for="name" class="control-label col-xs-2">Nome</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('name'));?>
	</div>
</div>


<div class="form-group">
	<label for="description" class="control-label col-xs-2">Descrição</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('description'));?>
	</div>
</div>

<div class="form-group">
	<label for="openHour" class="control-label col-xs-2">Horário</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
<?php echo $this->formRow($form->get('openHour'));?>
<h6>ate</h6>
<?php echo $this->formRow($form->get('closeHour'));?>
	</div>
</div>

<div class="form-group">
	<label for="visitDuration" class="control-label col-xs-2">Duração</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('visitDuration'));?>
	</div>
</div>

<div class="form-group">
	<label for="gps_lat" class="control-label col-xs-2">Latitude</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('gps_lat'));?>
	</div>
</div>

<div class="form-group">
	<label for="gps_long" class="control-label col-xs-2">Longitude</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('gps_long'));?>
	</div>
</div>

<div class="form-group">
	<label for="altitude" class="control-label col-xs-2">Altitude</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('altitude'));?>
	</div>
</div>

<div class="form-group">
	<label for="connectedPois" class="control-label col-xs-2">Ligações</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('connectedPois'));?>
	</div>
</div>

<div class="form-group">
	<label for="hashtags" class="control-label col-xs-2">Hashtags</label>
	<div>
<?php

echo $this->formRow($form->get('hashtags'));

$this->inlineScript()->captureStart();
echo <<<JS
    $('#hashtags').tagEditor({
                 			    initialTags: [],
                 			    placeholder: 'Enter tags ...'
                });
JS;
$this->inlineScript()->captureEnd();
?>
	</div>
</div>
<div class="form-group">
	<div class="col-xs-offset-2 col-xs-10">
		<?php echo $this->formSubmit($form->get('submit'));?>
	</div>
</div>
<?php echo $this->form()->closeTag();?>
	