//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Percurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Percurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary.Resources.Percurso", typeof(Percurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Hour.
        /// </summary>
        public static string FinishHour {
            get {
                return ResourceManager.GetString("FinishHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Route.
        /// </summary>
        public static string GenerateRoute {
            get {
                return ResourceManager.GetString("GenerateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Inclination (%).
        /// </summary>
        public static string Inclination {
            get {
                return ResourceManager.GetString("Inclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate a valid route with the given data, please try again..
        /// </summary>
        public static string InvalidResult {
            get {
                return ResourceManager.GetString("InvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must type the Max. Inclination.
        /// </summary>
        public static string MaxInclination_Error {
            get {
                return ResourceManager.GetString("MaxInclination_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must type the Max. Kilometers.
        /// </summary>
        public static string MaxKilometers_Error {
            get {
                return ResourceManager.GetString("MaxKilometers_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data for route generation.
        /// </summary>
        public static string MissingData {
            get {
                return ResourceManager.GetString("MissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On foot.
        /// </summary>
        public static string OnFoot {
            get {
                return ResourceManager.GetString("OnFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing through.
        /// </summary>
        public static string Passing {
            get {
                return ResourceManager.GetString("Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description can not be more than 250 characters.
        /// </summary>
        public static string Percurso_Description_Error {
            get {
                return ResourceManager.GetString("Percurso_Description_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be more than 50 characters.
        /// </summary>
        public static string Percurso_Name_Error {
            get {
                return ResourceManager.GetString("Percurso_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POIs of Route.
        /// </summary>
        public static string PercursoPOIs {
            get {
                return ResourceManager.GetString("PercursoPOIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select POI to Visit.
        /// </summary>
        public static string POIList_Error {
            get {
                return ResourceManager.GetString("POIList_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POI to Visit.
        /// </summary>
        public static string POIToVisit {
            get {
                return ResourceManager.GetString("POIToVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select and option to generate a valid route..
        /// </summary>
        public static string RouteMsg {
            get {
                return ResourceManager.GetString("RouteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an option to generate a Route.
        /// </summary>
        public static string RouteOption {
            get {
                return ResourceManager.GetString("RouteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on a POI List to visit.
        /// </summary>
        public static string RouteOption1 {
            get {
                return ResourceManager.GetString("RouteOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the route duration.
        /// </summary>
        public static string RouteOption2 {
            get {
                return ResourceManager.GetString("RouteOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Route.
        /// </summary>
        public static string RouteResult {
            get {
                return ResourceManager.GetString("RouteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Hour.
        /// </summary>
        public static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must choose a Starting Hour.
        /// </summary>
        public static string StartHour_Error {
            get {
                return ResourceManager.GetString("StartHour_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start POI.
        /// </summary>
        public static string StartPOI {
            get {
                return ResourceManager.GetString("StartPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuk.
        /// </summary>
        public static string Tuk {
            get {
                return ResourceManager.GetString("Tuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Duration.
        /// </summary>
        public static string VisitLength {
            get {
                return ResourceManager.GetString("VisitLength", resourceCulture);
            }
        }
    }
}
