//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class POI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal POI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary.Resources.POI", typeof(POI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude (m).
        /// </summary>
        public static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Hour.
        /// </summary>
        public static string CloseHour {
            get {
                return ResourceManager.GetString("CloseHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected POIs.
        /// </summary>
        public static string ConnectedPOIs {
            get {
                return ResourceManager.GetString("ConnectedPOIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string GPS_Lat {
            get {
                return ResourceManager.GetString("GPS_Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string GPS_Long {
            get {
                return ResourceManager.GetString("GPS_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtags.
        /// </summary>
        public static string Hashtags {
            get {
                return ResourceManager.GetString("Hashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationData {
            get {
                return ResourceManager.GetString("LocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Hour.
        /// </summary>
        public static string OpenHour {
            get {
                return ResourceManager.GetString("OpenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string OperationHour {
            get {
                return ResourceManager.GetString("OperationHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Altitude.
        /// </summary>
        public static string POI_Altitude_Error {
            get {
                return ResourceManager.GetString("POI_Altitude_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description can not be more than 250 characters.
        /// </summary>
        public static string POI_Description_Error {
            get {
                return ResourceManager.GetString("POI_Description_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Latitude.
        /// </summary>
        public static string POI_Lat_Error {
            get {
                return ResourceManager.GetString("POI_Lat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Longitude.
        /// </summary>
        public static string POI_Long_Error {
            get {
                return ResourceManager.GetString("POI_Long_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be more than 50 characters.
        /// </summary>
        public static string POI_Name_Error {
            get {
                return ResourceManager.GetString("POI_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Visit (min).
        /// </summary>
        public static string VisitDuration {
            get {
                return ResourceManager.GetString("VisitDuration", resourceCulture);
            }
        }
    }
}
