<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PortoVisitas\Module'                        => __DIR__ . '/Module.php',
    'PortoVisitas\Controller\POIController' => __DIR__ . '/src/PortoVisitas/Controller/POIController.php',
    'PortoVisitasTest\Framework\TestCase'        => __DIR__ . '/tests/PortoVisitas/Framework/TestCase.php',
    'PortoVisitasTest\SampleTest'                => __DIR__ . '/tests/PortoVisitas/SampleTest.php',
);
