<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Porto Visitas'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))?>

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>

    </head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">

			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('PortoVisitas') ?></a>

			</div>


			<div class="collapse navbar-collapse">
                <?php
                echo $this->navigation('Zend\Navigation\Default')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setUlClass('nav navbar-nav');
                
                if (session_status() == PHP_SESSION_NONE) {
                    session_start();
                }
                if (isset($_SESSION['user'])) {
                    
                    $page = $this->navigation('Zend\Navigation\Session')->getContainer()->findOneByAction('info');
                    $page->__set('label', $_SESSION['user']);
                    echo $this->navigation('Zend\Navigation\Session')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav navbar-right');
                } else {
                    
                    echo $this->navigation('Zend\Navigation\Guest')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav navbar-right');
                }
                ?>
			</div>

		</div>
		<!--/.nav-collapse -->
	</nav>
	<div class="container">
            <?php echo $this->content; ?>
            <hr>
		<footer>
			<p>2017 PortoVisitas. <?php echo $this->translate('All rights reserved.') ?></p>
		</footer>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>

