<?php
$title = 'Transferências';
$this->headTitle($title);
?>
<div class="container">
	<h4><?php echo $this->escapehtml($title);?></h4>
	<p>&nbsp;</p>

	<img src="/PortoVisitas/transfer/graphics.png"
		alt="Visualizador de Percurso" height="360" width="640"
		class="center-block">

	<p>&nbsp;</p>
	<p>&nbsp;</p>

	<button type="button" class="btn btn-default btn-lg center-block"
		onclick="window.location.href='/PortoVisitas/transfer/graphical_preview.zip'">
		<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
		Transferir Visualizador de Percurso
	</button>
</div>
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>