<head>
<meta charset="utf-8">
        <?php
        $title = 'Perfil';
        $this->headTitle($title);
        ?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink()
            ->prependStylesheet($this->basePath('css/jquery.tag-editor.css'))?>

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.tag-editor.min.js'))
            ->prependFile($this->basePath('js/jquery.caret.min.js'));
        ?>

	<script type="text/javascript">

	function logTag(field, editor, tags, poiJson) {
		console.log("Will update "+poiJson['name']+" with the tags:");
        for (var i = 0; i < tags.length; i++)
            console.log(tags[i]);
	}
	
	function savePOI(poiJson, tags) {
		var hashTags = new Array();
		for (var i = 0; i < tags.length; i++) {
			var tag = new Object();
			tag.Text = tags[i];
			hashTags[i] = tag;
		}
		poiJson['hashtags'] = hashTags;
		$.ajax({
			type: 'PUT',
			cache: false,
			url: "http://10.8.11.86/PVAPI/api/POI/"+poiJson['poiid'],
			data: poiJson,
			async: true,
			crossDomain: true,
			error: function (error) {
				if (error.status == 401) {
					alert('Unauthorized');
				} else {
					alert('Error Updating POI: ' + error.responseText);
				}
			},
		});

	}
	
	</script>

</head>


<h3><?php echo $this->escapeHtml($title); ?></h3><h5><b><font color="grey"><?php echo $this->escapeHtml($mail);?></font></b></h5>

<br/>
<b>
<?php echo "Os meus Pontos de Interesse: ";?>
</b>
<p>
<br/>

<table class="table">
	<tr>
		<th>Estado</th>
		<th>Nome</th>
		<th>Descricao</th>
		<th>Horario</th>
		<th>Duracao (min)</th>
		<th>Coordenadas</th>
		<th>Altitude (m)</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($pois as $poi) : ?>
	<tr>
		<?php
          if ($poi->approved == null) {
         ?>
          <td><font color="blue">Submetido</font></td>
         <?php
          } else if ($poi->approved == "no") {
          ?>
          <td><font color="red">Rejeitado</font></td>
          <?php
          } else {
          ?>
          <td><font color="green">Aprovado</font></td>
          <?php
          }
          ?>
 		<td><?php echo $this->escapeHtml($poi->name);?></td>
 		<td style="width: 30%;"><?php echo $this->escapeHtml($poi->description);?></td>
 		<?php
 		     $openDate = date_parse($poi->openHour);
 		     $opens = $openDate['hour'].":".$openDate['minute'];
 		     $closeDate = date_parse($poi->closeHour);
 		     $closes = $closeDate['hour'].":".$closeDate['minute'];
 		     $schedule = date('H:i',strtotime($opens))." - ".date ('H:i',strtotime($closes));
 		?>
 		<td><?php echo $this->escapeHtml($schedule);?></td>
 		<td><?php echo $this->escapeHtml($poi->visitDuration);?></td>
 		<td><?php echo $this->escapeHtml($poi->gps_lat.",".$poi->gps_long);?></td>
 		<td><?php echo $this->escapeHtml($poi->altitude);?></td>
 		</tr>
 		
 			<tr>
 		<td colspan="2" style="border:none;text-align:right;">
 			<div class="tagsDiv" style="padding-bottom:30px;">
 				<label for="hashtags_<?php echo $poi->poiid?>">
 					<font color="lightgrey" style="font:menu;">Hashtags</font>
 				</label>
 			</div>
 		</td>
 		<td colspan="5" style="border:none;">
        <input type="text" name="tags_<?php echo $poi->poiid?>" id="hashtags_<?php echo $poi->poiid?>">
 			<?php
 			$tags = (null != $poi->hashtags) ? array_column($poi->hashtags, 'Text') : [];
 			$htags = json_encode($tags, JSON_HEX_TAG);
 			$poiJson = json_encode($poi);
 			$this->inlineScript()->captureStart();
 			
 			echo <<<JS
    $('#hashtags_$poi->poiid').tagEditor({
                 			    initialTags: $htags,
                 			    placeholder: 'Enter tags ...',
                                onChange: function(field, editor, tags) {
                                    //logTag(field, editor, tags, $poiJson);
                                    savePOI($poiJson, tags);    
                                }

                });
JS;
            $this->inlineScript()->captureEnd();
     		?>
 		</td>
	</tr>
 		
	
<?php endforeach; ?>
</table>
