<head>
<meta charset="utf-8">
        <?php
        $title = 'Perfil';
        $this->headTitle($title);
        ?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink()
            ->prependStylesheet($this->basePath('css/jquery.tag-editor.css'))?>

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.tag-editor.min.js'))
            ->prependFile($this->basePath('js/jquery.caret.min.js'));
        ?>

	<script type="text/javascript">

	function logTag(field, editor, tags, poiJson) {
		console.log("Will update "+poiJson['Name']+" with the tags:");
        for (var i = 0; i < tags.length; i++)
            console.log(tags[i]);

        console.log(poiJson);
	}
	
	function savePOI(poiJson, tags) {
		var hashTags = new Array();
		for (var i = 0; i < tags.length; i++) {
			var tag = new Object();
			tag.Text = tags[i];
			hashTags[i] = tag;
		}
		poiJson['Hashtags'] = hashTags;
		poiJson['POIID'] = poiJson['ID'];
        delete poiJson['ID'];
		$.ajax({
			type: 'PUT',
			cache: false,
			url: "http://10.8.11.86/PVAPI/api/POI/"+poiJson['POIID'],
			data: poiJson,
			async: true,
			crossDomain: true,
// 			success: function (result) {
// 				handler(result.access_token);
// 			},
			error: function (error) {
				if (error.status == 401) {
					alert('Unauthorized');
				} else {
					alert('Error Updating POI: ' + error.responseText);
				}
			}
		});

	}
	
	</script>

    </head>

<h2><?php echo $this->escapeHtml($title); ?></h2><b><font color="grey"><h4><?php echo $this->escapeHtml($mail);?></h4></font></b>

<br/>
<b>
<?php echo "Os meus Pontos de Interesse: ";?>
</b>
<p>
<br/>

<table class="table">
	<tr>
		<th>Estado</th>
		<th>Nome</th>
		<th>Descricao</th>
		<th>Horario</th>
		<th>Duracao (min)</th>
		<th>Coordenadas</th>
		<th>Altitude (m)</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($pois as $poi) : ?>
	<tr>
		<?php
          if ($poi->Approved == null) {
         ?>
          <td><font color="blue">Submetido</font></td>
         <?php
          } else if ($poi->Approved == "no") {
          ?>
          <td><font color="red">Rejeitado</font></td>
          <?php
          } else {
          ?>
          <td><font color="green">Aprovado</font></td>
          <?php
          }
          ?>
 		<td><?php echo $this->escapeHtml($poi->Name);?></td>
 		<td style="width: 30%;"><?php echo $this->escapeHtml($poi->Description);?></td>
 		<?php
 		     $openDate = date_parse($poi->OpenHour);
 		     $opens = $openDate['hour'].":".$openDate['minute'];
 		     $closeDate = date_parse($poi->CloseHour);
 		     $closes = $closeDate['hour'].":".$closeDate['minute'];
 		     $schedule = date('H:i',strtotime($opens))." - ".date ('H:i',strtotime($closes));
 		?>
 		<td><?php echo $this->escapeHtml($schedule);?></td>
 		<td><?php echo $this->escapeHtml($poi->VisitDuration);?></td>
 		<td><?php echo $this->escapeHtml($poi->GPS_Lat.",".$poi->GPS_Long);?></td>
 		<td><?php echo $this->escapeHtml($poi->Altitude);?></td>
 		</tr>
 		
 			<tr>
 		<td colspan="2" style="border:none;text-align:right;">
 			<div class="tagsDiv" style="padding-bottom:30px;">
 				<label for="hashtags_<?php echo $poi->ID?>">
 					<font color="lightgrey" style="font:menu;">Hashtags</font>
 				</label>
 			</div>
 		</td>
 		<td colspan="5" style="border:none;">
        <input type="text" name="tags_<?php echo $poi->ID?>" id="hashtags_<?php echo $poi->ID?>">
 			<?php
 			$tags = array_column($poi->Hashtags, 'Text');
 			$htags = json_encode($tags, JSON_HEX_TAG);
 			$poiJson = json_encode($poi);
 			$this->inlineScript()->captureStart();
 			
 			echo <<<JS
    $('#hashtags_$poi->ID').tagEditor({
                 			    initialTags: $htags,
                 			    placeholder: 'Enter tags ...',
                                onChange: function(field, editor, tags) {
                                    //logTag(field, editor, tags, $poiJson);
                                    savePOI($poiJson, tags);    
                                }

                });
JS;
            $this->inlineScript()->captureEnd();
     		?>
 		</td>
	</tr>
 		
	
<?php endforeach; ?>
</table>
