<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',
$this->url('user', array('action' => 'login')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
	<label for="email" class="control-label col-xs-2">Email</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('email'));?>
	</div>
</div>

<div class="form-group">
	<label for="password" class="control-label col-xs-2">Password</label>
	<div class="col-xs-5 col-sm-6 col-lg-4">
		<?php echo $this->formRow($form->get('password'));?>
	</div>
</div>

<div class="form-group">
	<div class="col-xs-offset-2 col-xs-10">
		<?php echo $this->formSubmit($form->get('submit'));?>
	</div>
</div>

<?php echo $this->form()->closeTag();?>