<?php
$title = 'Cancelar Visita';
$this->headTitle($title);
?>
 <h4><?php echo $this->escapeHtml($title); ?></h4>

 <p>Tem a certeza que pretende eliminar
     <b><?php echo $this->escapeHtml($visita['Percurso']['Name']); ?></b> ?
 </p>
 <?php
 $url = $this->url('visita', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $visita['VisitaID']; ?>" />
     <input type="submit" name="del" value="Sim" />
     <input type="submit" name="del" value="Nao" />
 </div>
 </form>