<?php
$title = 'Editar Visita';
$this->headTitle($title);

// $form->setAttribute('action', $this->url('visita', array(
//     'action' => 'add'
// )));
?>

<h4><?php echo $this->escapehtml('Agendamento do percurso \''.$percurso['Name'].'\'')?></h4>
<p>&nbsp;</p>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div id="formDiv" class="container">
<?php

echo $this->formHidden($form->get('visitaID'));
echo $this->formHidden($form->get('creator'));
echo $this->formHidden($form->get('percurso'));
?>

	<div class="form-group">
		<label for="name" class="control-label col-xs-4">Escolha uma data para
			a Visita</label>
		<div class="col-xs-5 col-sm-6 col-lg-4">
			<?php echo $this->formRow($form->get('date'));?>
		</div>
	</div>


	<div class="form-group">
		<div class="col-xs-10" style="margin-left: 21%">
			<?php echo $this->formSubmit($form->get('cancel'));?>
			<?php echo $this->formSubmit($form->get('submit'));?>
		</div>
	</div>

</div>

<?php echo $this->form()->closeTag();?>
